# Generated by Django 3.2.8 on 2021-10-17 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houseplants_api', '0003_waterplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='WaterPlan',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_plans', to='houseplants_api.plant'),
        ),
    ]
